openapi: 3.0.0
info:
  title: Docs API Karohy
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Authentification - User
  - name: Authentification - Admin
paths:
  /api/v1/users/login:
    post:
      tags:
        - Authentification - User
      summary: API to log in User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: cedric@gmail.com
                password: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                success: true
                message: Successfully connected
                datas:
                  user:
                    _id: bazdaz56586
                    firstname: Rabarijohn
                    lastname: Cedric
                    email: cedric@gmail.com
                    birth_date: '2002-02-02T00:00:00.000Z'
                    phone_number: '0345387866'
        '400':
          description: Failed response
          content:
            application/json:
              example:
                success: false
                message: Incorrect email or password
                datas: null
                error:
                  code: ERROR_AUTH_USER_DENIED
                  message: Authentication failed, user or password is invalid
  /api/v1/users/register:
    post:
      tags:
        - Authentification - User
      summary: API to register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstname: Test
                lastname: lastnameTest
                email: test@gmail.com
                password: '1234'
                birth_date: '2002-02-02'
                phone_number: '0334587956'
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              example:
                success: true
                message: Registered user successfully
                datas:
                  _id: adazdaz5as47855da
                  firstname: Test
                  lastname: lastnameTest
                  email: test@gmail.com
                  birth_date: '2002-02-02T00:00:00.000Z'
                  phone_number: '0345387866'
        '400':
          description: Failed response
          content:
            application/json: 
              example:
                success: false
                message: An error occured while registering user
                error:
                  code: SOME_ERROR_CODE
                  message: Error message
  /api/v1/admin/login:
    post:
      tags:
        - Authentification - Admin
      summary: API to log in Admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: admin@gmail.com
                password: admin
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '400':
          description: Failed response
          content:
            application/json: {}
